name: 'Fastn Deploy Flow'
description: 'Github Action for deploying flows'
author: 'Fastn Inc.'

# Define your inputs here.
inputs:
  source-domain:
    description:
      'Fastn environment URI from where to fetch the flow e.g. qa.fastn.ai,
      prod.fastn.ai'
    required: true
  source-project-id:
    description: 'Project ID where the flow to deploy is present'
    required: true
  source-flow-name:
    description:
      'Optional - Name of the flow to deploy. For multiple flows a comma
      seperated list can be used e.g. flow1,flow2. If name is not provided all
      flows will be fetched from source stage and deployed'
  source-stage:
    description:
      'Optional - stage from where to pick the flows. e.g. QA, DRAFT, LIVE'
    default: 'LIVE'
  source-account-username:
    description:
      'Username of the account from where the flow to deploy is present'
    required: true
  source-account-password:
    description:
      'Password of the account from where the flow to deploy is present'
    required: true
  resources-to-export:
    description:
      'Config for which resources to export e.g. ALL, FLOWS, MODELS, CONNECTORS'
    default: 'ALL'
  destination-domain:
    description:
      'Fastn environment from where to deploy the flow e.g. qa.fastn.ai,
      prod.fastn.ai'
    required: true
  destination-project-id:
    description: 'Project ID where the flow will be deployed'
    required: true
  destination-stage:
    description:
      'Optional - stage where to deploy the flows. e.g. QA, DRAFT, LIVE'
    default: 'LIVE'
  destination-account-username:
    description: 'Username of the account where the flow will be deployed'
    required: true
  destination-account-password:
    description: 'Password of the account where the flow will be deployed'
    required: true

runs:
  using: node20
  main: dist/index.js
