name: Continuous Integration

on:
  workflow_dispatch:
    inputs:
      source-domain:
        required: true
        type: string
        description: 'source-domain'
      source-project-id:
        required: true
        type: string
        description: 'source-project-id'
      source-account-username:
        required: true
        type: string
        description: 'source-account-username'
      source-account-password:
        required: true
        type: string
        description: 'source-account-password'
      source-flow-name:
        type: string
        description: 'source-flow-name'
      destination-domain:
        required: true
        type: string
        description: 'destination-domain'
      destination-project-id:
        required: true
        type: string
        description: 'destination-project-id'
      destination-account-username:
        required: true
        type: string
        description: 'destination-account-username'
      destination-account-password:
        required: true
        type: string
        description: 'destination-account-password'

permissions:
  contents: read

jobs:
  test-action:
    name: GitHub Actions Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4

      - name: Test Local Action
        id: test-action
        uses: ./
        with:
          source-domain: ${{ github.event.inputs.source-domain }}
          source-project-id: ${{ github.event.inputs.source-project-id }}
          source-account-username:
            ${{ github.event.inputs.source-account-username }}
          source-account-password:
            ${{ github.event.inputs.source-account-password }}
          source-flow-name: ${{ github.event.inputs.source-flow-name}}
          destination-domain: ${{ github.event.inputs.destination-domain }}
          destination-project-id:
            ${{ github.event.inputs.destination-project-id }}
          destination-account-username:
            ${{ github.event.inputs.destination-account-username }}
          destination-account-password:
            ${{ github.event.inputs.destination-account-password }}
