name: Continuous Integration

on:
  workflow_dispatch:
    inputs:
      source-env:
        required: true
        type: string
        description: 'source-env'
      source-project-id:
        required: true
        type: string
        description: 'source-project-id'
      source-flow-name:
        required: true
        type: string
        description: 'source-flow-name'
      source-account-username:
        required: true
        type: string
        description: 'source-account-username'
      source-account-password:
        required: true
        type: string
        description: 'source-account-password'
      destination-env:
        required: true
        type: string
        description: 'destination-env'
      destination-project-id:
        required: true
        type: string
        description: 'destination-project-id'
      destination-account-username:
        required: true
        type: string
        description: 'destination-account-username'
      destination-account-password:
        required: true
        type: string
        description: 'destination-account-password'

permissions:
  contents: read

jobs:
  test-javascript:
    name: JavaScript Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        id: setup-node
        uses: actions/setup-node@v4
        with:
          node-version-file: .node-version
          cache: npm

      - name: Install Dependencies
        id: npm-ci
        run: npm ci

      - name: Check Format
        id: npm-format-check
        run: npm run format:check

      - name: Lint
        id: npm-lint
        run: npm run lint

      - name: Test
        id: npm-ci-test
        run: npm run ci-test

  test-action:
    name: GitHub Actions Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4

      - name: Test Local Action
        id: test-action
        uses: ./
        with:
          source-env: ${{ github.event.inputs.source-env }}
          source-project-id: ${{ github.event.inputs.source-project-id }}
          source-flow-name: ${{ github.event.inputs.source-flow-name }}
          source-account-username:
            ${{ github.event.inputs.source-account-username }}
          source-account-password:
            ${{ github.event.inputs.source-account-password }}
          destination-env: ${{ github.event.inputs.destination-env }}
          destination-project-id:
            ${{ github.event.inputs.destination-project-id }}
          destination-account-username:
            ${{ github.event.inputs.destination-account-username }}
          destination-account-password:
            ${{ github.event.inputs.destination-account-password }}
